export const MOVIE_INFO = `MOVIE_INFO`
export const MOVIES_FETCH = `MOVIES_FETCH`
export const POPULAR_MOVIES_ADD = `POPULAR_MOVIES_ADD`;
export const TOP_MOVIES_ADD = `TOP_MOVIES_ADD`
export const ADD_CONFIG_TO_STORE = `ADD_CONFIG_TO_STORE`;
export const RECEIVE_CONFIG = `RECEIVE_CONFIG`;
export const RECEIVE_MOVIE_DATA = `RECEIVE_MOVIE_DATA`; 