export const MOVIE_INFO = `MOVIE_INFO`
export const MOVIES_FETCH = `MOVIES_FETCH`
export const POPULAR_MOVIES_ADD = `POPULAR_MOVIES_ADD`;
export const TOP_MOVIES_ADD = `TOP_MOVIES_ADD`
export const MOVIE_CONFIG = `MOVIE_CONFIG`;
export const CONFIG_UPDATE = `CONFIG_UPDATE`;
export const RECEIVE_MOVIE_DATA = `RECEIVE_MOVIE_DATA`; 